[package]
name = "chip-8"
version = "0.1.0"
authors = ["Erik Higginbotham <erik96@me.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "0.34.3"
rand = "0.8.0"
